### ISSUE TITLE
Examples and docs

### ISSUE THREAD

**Issue by metalaureate** [chilts/awssum-amazon-fps#1]
Hi - I was looking for http://stackoverflow.com/questions/17386404/amazon-fps-sdk-ports-for-node-js/17391398#17391398

and answered the question myself with your package.

But, I am a bit confused about the documentation for implementing Amazon FPS - "There are intro programs, examples and full docs in each plugin's repository, so please read them for specific instructions for each plugin."

Are there any for FPS? I don't see any other than a single file that I don't understand how to use.

I've had some experience in the past with implementing FPS with the Amazon's own PHP SDK  - it provides about two dozen example functions for every kind of payment, similar to what you provide with S3. Where would I get started with your package?

Thanks.

**Comment by chilts** [comment]
Hi Simon,

I'll try and add some examples to the readme for you tonight. Sorry about that. :)

Glad you found the project.

Cheers,
Andy

**Comment by metalaureate** [comment]
That would be a great service to humanity - thank you so much!

**Comment by metalaureate** [comment]
I'm clutching at straws, but if you had a second to help me out on Stack Exchange below, I'd be much in your debt.

http://stackoverflow.com/questions/17497981/how-to-sign-amazon-simple-pay-button-in-node-js-javascript

**Comment by chilts** [comment]
(deprecated: use aws-sdk)
