### ISSUE TITLE
TransactionAmount/SettleAmount should be a complex value vs simple value

### ISSUE THREAD

**Issue by mphilpot** [chilts/awssum-amazon-fps#2]
When sending a paid request I was getting the following error.

// console.log(util.inspect(err.Body.Response.Errors)
{ Error: 
   { Code: 'InvalidParams',
     Message: 'transactionAmount.amount can not be null' } }

To fix this you can either flip Transaction amount to a param-data or expand out to TransactionAmount.Value && TransactionAmount.CurrencyCode (which looks to be the default in this file/module/plugin).

**Comment by chilts** [comment]
(deprecated: use aws-sdk)
